CREATE TABLE Cursos (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(100) NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at DATE NOT NULL,
    updated_at DATE NULL,
    PRIMARY KEY(id)
);